# Generated by Django 2.2.3 on 2019-10-24 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('sunday', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('time', models.TimeField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('max_health', models.PositiveSmallIntegerField(default=0)),
                ('current_health', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('head', models.BooleanField(default=False)),
                ('neck', models.BooleanField(default=False)),
                ('shoulder', models.BooleanField(default=False)),
                ('chest', models.BooleanField(default=False)),
                ('arm', models.BooleanField(default=False)),
                ('hand', models.BooleanField(default=False)),
                ('belt', models.BooleanField(default=False)),
                ('waist', models.BooleanField(default=False)),
                ('leg', models.BooleanField(default=False)),
                ('feet', models.BooleanField(default=False)),
                ('accessory', models.BooleanField(default=False)),
                ('wallet', models.IntegerField(default=0)),
                ('brawny', models.PositiveSmallIntegerField(default=0)),
                ('sturdy', models.PositiveSmallIntegerField(default=0)),
                ('speedy', models.PositiveSmallIntegerField(default=0)),
                ('nerdy', models.PositiveSmallIntegerField(default=0)),
                ('balky', models.PositiveSmallIntegerField(default=0)),
                ('wily', models.PositiveSmallIntegerField(default=0)),
                ('pritty', models.PositiveSmallIntegerField(default=0)),
                ('gritty', models.PositiveSmallIntegerField(default=0)),
                ('witty', models.PositiveSmallIntegerField(default=0)),
                ('beastly', models.PositiveSmallIntegerField(default=0)),
                ('techy', models.PositiveSmallIntegerField(default=0)),
                ('outdoorsy', models.PositiveSmallIntegerField(default=0)),
                ('arrivad', models.BooleanField(default=False)),
                ('basahnin', models.BooleanField(default=False)),
                ('ferrick', models.BooleanField(default=False)),
                ('holeg', models.BooleanField(default=False)),
                ('human', models.BooleanField(default=False)),
                ('illawmi', models.BooleanField(default=False)),
                ('kassari', models.BooleanField(default=False)),
                ('khura', models.BooleanField(default=False)),
                ('mogo', models.BooleanField(default=False)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
