# Generated by Django 2.2.3 on 2019-10-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0002_auto_20191029_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='arm',
        ),
        migrations.RemoveField(
            model_name='character',
            name='feet',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='character',
            name='leg',
        ),
        migrations.AddField(
            model_name='character',
            name='left_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='left_foot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='left_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='left_leg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='right_arm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='right_foot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='right_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='right_leg',
            field=models.BooleanField(default=False),
        ),
    ]
