# Generated by Django 2.2.3 on 2019-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0003_auto_20191029_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='playable',
            field=models.BooleanField(default=True),
        ),
    ]
