# Generated by Django 2.2.3 on 2019-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0004_character_playable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='troubleshooting',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='navigating',
            new_name='guiding',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='lifinting',
            new_name='lifting',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='tumbling',
            new_name='moving',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='sensing',
            new_name='observing',
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='hussle',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
