# Generated by Django 2.2.3 on 2019-10-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0005_auto_20191029_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.CharField(default='R', max_length=16),
            preserve_default=False,
        ),
    ]
