# Generated by Django 2.2.3 on 2019-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0006_room_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='room',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Sun', max_length=16),
            preserve_default=False,
        ),
    ]
