# Generated by Django 2.2.3 on 2019-11-02 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0007_auto_20191029_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_activity',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 17, 5, 54, 913267)),
            preserve_default=False,
        ),
    ]
